// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // migrate/generate 등 CLI 명령은 여기서 연결함 — transaction pooler(DATABASE_URL, pgbouncer)는
    // 마이그레이션에 필요한 세션 기능(advisory lock 등)을 지원하지 않아서 반드시 DIRECT_URL(session pooler) 사용.
    url: process.env["DIRECT_URL"]!,
  },
});
